Solve sim speed
acrlabs/simkube pull request #144
Opened 2024-10-23 21:35 UTC by GeraldoSJr

- [x] I certify that this PR does not contain any code that has been generated with GitHub Copilot or any other AI-based code generation tool, in accordance with this project's policies.

## Description
This PR fix the issue Run simulation at different speeds by adding a argument, sim_step_duration, to the cli and passing this argument to the run_trace function and allowing the simulation to run on this speed instead of the fixed timestamp speed specified on the trace.

## Testing done
- How did you test your changes? Manually deployed the code and ran simulation with different parameters and speeds to measure the impact of the fix.
- Does this code require any new tests to be written? No.

## Additional info
Resolves #76

2024-10-23 21:35 UTC, drmorr0 commented
<!-- 🔥config summary -->
## Updating Kubernetes DAG...
Please wait until the job has finished.

2024-10-24 01:27 UTC, drmorr0 requested changes
Hi, @GeraldoSJr, thank you for the PR!  Can you please update code changes so that instead of using a "stepwise" function, the speed is controlled by a constant factor?  I.e., 

```
let sleep_duration = max(0, (next_ts - sim_ts) / speed_factor);
```

This way we're guaranteed that, with a speed factor of 2, that the simulation will run exactly twice as fast.

2024-10-24 01:28 UTC, drmorr0 commented on .gitignore
> +Makefile
Makefile/build shouldn't be in .gitignore

2024-10-24 02:24 UTC, GeraldoSJr commented
Added the changes requested, that was actually my innitial approach, changed midway to resolve the issue more directly, anyways, hope this will solve it now. Just wanted to say that I'm excited to start helping in the repo, really nice project! 👍

2024-10-24 21:28 UTC, drmorr0 requested changes
Hi -- a few small changes, but this is basically there.  Thanks!

2024-10-24 21:28 UTC, drmorr0 commented on Makefile
> +
Can we delete the extraneous whitespace?

2024-10-24 21:28 UTC, drmorr0 commented on sk-driver/src/runner.rs
> +pub async fn run_trace(ctx: DriverContext, client: kube::Client, speed: f64) -> EmptyResult {
since the `speed` value is attached to the simulation custom resource, we can read it directly from there (e.g., `ctx.sim.spec.speed`) instead of passing it in as an extra parameter.

2024-10-24 21:28 UTC, drmorr0 commented on sk-driver/src/runner.rs
> +            let sleep_duration = max(0, sleep_duration);
I think we can simplify this whole thing significantly:

```
let simulation_normal_step_duration = max(0, next_ts - sim_ts) as f64;
let sleep_duration = (simulation_normal_step_duration / speed).round() as u64;
```

That way we ensure that even if there's a negative step duration, that event will happen "right now"; and speed should never be negative at this point (ideally we'd have some validation here, but that can be done in a different PR).

2024-10-25 05:06 UTC, drmorr0 approved these changes

2024-10-25 05:07 UTC, merged