Update README.md with git submodule commands
acrlabs/simkube pull request #49
Opened 2023-11-08 06:10 UTC by bizzybits

## issue
when following README as is, I ran into a `no such file or directory` error when attempting the build step. 
```
➜  simkube git:(master) make build
Makefile:19: build/base.mk: No such file or directory
make: *** No rule to make target `build/base.mk'.  Stop.
```
## proposed solution
add in `git submodule init` and `git submodule update` to building section in README.md to fix build file missing error when setting up simkube.

## testing
with all prerequisites installed as listed in the README:
- created test directory 
- cloned simkube
- ran `git init submodule`, `git init update`, `make build`, and `make skctl` from the root directory

```
➜  simkube git:(master) git submodule init
Submodule 'build' (https://github.com/acrlabs/build-scripts) registered for path 'build'
➜  simkube git:(master) git submodule update 
Cloning into '/Users/pepper/simbuke2/simkube/build'...
Submodule path 'build': checked out 'eea4f8400c9f1b2b20b9461732e5c174e650f2bd'
➜  simkube git:(master) make build 
...
 Compiling simkube v0.7.0 (/build)
    Finished dev [unoptimized + debuginfo] target(s) in 27.87s
cp /build/.build/debug/sk-tracer /build/.build/.
➜  simkube git:(master) make skctl
CGO_ENABLED=0 go build -trimpath -o /Users/pepper/simbuke2/simkube/.build/skctl ./cli/
```

2023-11-08 14:40 UTC, drmorr0 requested changes

2023-11-08 14:40 UTC, drmorr0 commented on README.md
> +- `git submodule init && git submodule update`
can you add a note that you just need to do this once?

can you also add this step to the contributing doc? https://github.com/acrlabs/simkube/blob/master/docs/contributing.md#setup

2023-11-09 05:07 UTC, bizzybits commented on README.md
> +- `git submodule init && git submodule update`
yes! all set! 👍

2023-11-09 05:14 UTC, drmorr0 approved these changes

2023-11-09 05:14 UTC, merged